name: test-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./
      S3_BUCKET_NAME: dkdlcka
      CODE_DEPLOY_APPLICATION_NAME: testapp
      CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: homecoming-group
      
    steps:
      - name: Cheakout
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{env.working-directory}}
        
      - name: Build with Gradle
        run: ./gradlew bootjar
        shell: bash
        working-directory: ${{env.working-directory}}
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ${{env.working-directory}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./homecoming.zip s3://$S3_BUCKET_NAME/



    # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment 
          --application-name testapp
          --deployment-group-name homecoming-group
          --file-exists-behavior OVERWRITE 
          --s3-location bucket=dkdlcka,bundleType=zip,key=homecoming.zip
          --region ap-northeast-2
