name : test-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: 
    contents: read

env:
  S3_BUCKET_NAME: dkdlcka
  PROJECT_NAME: action_codedeploy
  RESOURCE_PATH: ./src/main/resources/application.yaml
  CODE_DEPLOY_APPLICATION_NAME: testapp
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: homecoming-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution : "temurin"
          


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        working-directory : ${{env.working-directory}}

      - name: Build with Gradle
        run: ./gradlew clean build

    # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy
        
    # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy
      
    # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy
        
     # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./homecoming.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./homecoming.zip s3://$S3_BUCKET_NAME/
        
     # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          aws deploy create-deployment 
          --application-name coinTalk[testapp] 
          --deployment-group-name coinTalk-group[homecoming-group] 
          --file-exists-behavior OVERWRITE 
          --s3-location bucket=cointalk-deploy[dkdlcka],bundleType=zip,key=coinTalk.zip[homecoming.zip] 
          --region ap-northeast-2
